import assert from 'node:assert/strict';
import { createReadStream } from 'node:fs';
import { access, mkdtemp, stat, writeFile } from 'node:fs/promises';
import http from 'node:http';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { ImageLibraryBuilder } from '../tools/build-image-library.mjs';

const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const REPOSITORY_ROOT = path.resolve(import.meta.dirname, '..');
const INTERFACE_ROOT = path.resolve(REPOSITORY_ROOT, '..', 'library-ui-bsns-ru');
const HOST = '127.0.0.1';
const SITE_PORT = 4191;
const INTERFACE_PORT = 4192;
const SITE_URL = `http://${HOST}:${SITE_PORT}/`;
const INTERFACE_URL = `http://${HOST}:${INTERFACE_PORT}/`;
const FIXTURE_COUNT = 34;
const EXPECTED_PAGE_COUNTS = Object.freeze([30, 4]);
const CLEAN_CYCLES = 3;
const FIRST_INDEX_FAILURES = 1;
const RESOURCE_API_PATH = '/resource-admin/api.php';
const RESOURCE_TYPE = 'resources';
const FIRST_PAGE = 1;
const STATIC_FALLBACK_ENDPOINT = `${SITE_URL}unavailable-api.php`;
const MIME_BY_EXTENSION = Object.freeze({ '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml' });

// Function: temporary images remain outside the repository and are generated by the same production builder.
async function fixtureLibrary() {
    const directory = await mkdtemp(path.join(os.tmpdir(), 'bzn-images-browser-'));
    for (let index = 0; index < FIXTURE_COUNT; index += 1) {
        // Loop: distinct SVG colors expose broken pagination or stale previews.
        const hue = (index * 37) % 360;
        const source = `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="240"><rect width="320" height="240" fill="hsl(${hue} 70% 45%)"/></svg>`;
        await writeFile(path.join(directory, `Browser ${String(index + 1).padStart(2, '0')}.svg`), source, 'utf8');
    }
    await new ImageLibraryBuilder(directory).build();
    return directory;
}

// Function: one server maps the repository shell and a separate generated content directory without mutating either.
function staticServer(root, port, contentRoot = null, options = {}) {
    let remainingIndexFailures = Number(options.indexFailures) || 0;
    const server = http.createServer(async (request, response) => {
        const requestUrl = new URL(request.url, `http://${HOST}`);
        const requestPath = decodeURIComponent(requestUrl.pathname);
        if (contentRoot && requestPath === RESOURCE_API_PATH) {
            // Branch: the fixture API has the same newest-first contract as the production Resource Engine.
            const page = Math.max(FIRST_PAGE, Number(requestUrl.searchParams.get('page')) || FIRST_PAGE);
            const pageSize = Math.max(FIRST_PAGE, Number(requestUrl.searchParams.get('page_size')) || EXPECTED_PAGE_COUNTS[0]);
            const names = Array.from({ length: FIXTURE_COUNT }, (_, index) => `Browser ${String(FIXTURE_COUNT - index).padStart(2, '0')}.svg`);
            const items = names.slice((page - FIRST_PAGE) * pageSize, page * pageSize).map((name, index) => ({
                id: `fixture-${index}`, type: RESOURCE_TYPE, name, mime: 'image/svg+xml',
                urls: { resource: `/images/${encodeURIComponent(name)}`, thumbnail: `/images/${encodeURIComponent(name)}` },
            }));
            response.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
            return response.end(JSON.stringify({ ok: true, type: RESOURCE_TYPE, page, page_size: pageSize, pages: Math.ceil(FIXTURE_COUNT / pageSize), total: FIXTURE_COUNT, items }));
        }
        const contentRequest = contentRoot && requestPath.startsWith('/images/');
        const relativePath = contentRequest ? requestPath.replace(/^\/images\//, '') : (requestPath === '/' ? 'index.html' : requestPath.replace(/^\/+/, ''));
        if (contentRequest && relativePath === 'files.js' && remainingIndexFailures > 0) {
            // Branch: production may receive FTP files before its generated index; the next Refresh must recover.
            remainingIndexFailures -= 1;
            return response.writeHead(404).end();
        }
        const selectedRoot = contentRequest ? contentRoot : root;
        const filePath = path.resolve(selectedRoot, relativePath);
        if (!filePath.startsWith(`${selectedRoot}${path.sep}`)) return response.writeHead(403).end();
        try {
            await access(filePath);
            if (!(await stat(filePath)).isFile()) throw new Error('not-file');
            response.setHeader('Content-Type', MIME_BY_EXTENSION[path.extname(filePath).toLowerCase()] || 'application/octet-stream');
            response.setHeader('Access-Control-Allow-Origin', '*');
            createReadStream(filePath).pipe(response);
        } catch {
            response.writeHead(404).end();
        }
    });
    return new Promise((resolve) => server.listen(port, HOST, () => resolve(server)));
}

// Function: browser configuration changes only the two physical hosts while keeping the production contract.
function browserConfiguration() {
    const interfacePaths = Object.freeze({
        resourceLibraryScript: 'assets/resource-library-v2.js', resourceLibraryStylesheet: 'assets/resource-library.css',
        libraryWindowScript: 'NewUI/Library_Window.js', libraryWindowConfiguration: 'NewUI/windows/library_window.json',
        libraryWindowFileBridge: 'NewUI/windows/library_window.data.js', lightboxScript: 'assets/lightbox.js', lightboxStylesheet: 'assets/lightbox.css',
    });
    return Object.freeze({
        siteRootUrl: SITE_URL, interfaceRootUrl: INTERFACE_URL,
        library: Object.freeze({ id: 'images', callerId: 'imageLibrary', contentType: 'Images', defaultTab: 'Images' }),
        globals: Object.freeze({ files: 'BZNLibraryImageFiles', resourceLibrary: 'BZNResourceLibrary', libraryRuntimeConfig: 'BZNLibraryRuntimeConfig', libraryWindow: 'BZNNewUILibraryWindow' }),
        data: Object.freeze({ indexWidth: 3, scriptExtension: '.js', previewKind: 'image', defaultMime: 'application/octet-stream' }),
        mimeByExtension: Object.freeze({ svg: 'image/svg+xml' }), labels: Object.freeze({ title: 'Библиотека изображений', use: 'Использовать' }),
        status: Object.freeze({ loading: 'Загрузка…', ready: 'Готово: {count} изображений.', empty: 'Индекс пока отсутствует.', error: 'Ошибка' }),
        imageDirectoryUrl: `${SITE_URL}images/`, imageIndexUrl: `${SITE_URL}images/files.js`,
        imageDataDirectoryUrl: `${SITE_URL}images/data/`,
        resourceEngine: Object.freeze({ clientScript: `${SITE_URL}resource-engine/resource-client.js`, endpoint: `${SITE_URL}${RESOURCE_API_PATH.slice(1)}`, type: RESOURCE_TYPE }),
        interface: Object.freeze(Object.fromEntries(Object.entries(interfacePaths).map(([key, value]) => [key, `${INTERFACE_URL}${value}`]))),
    });
}

const contentRoot = await fixtureLibrary();
const servers = await Promise.all([
    staticServer(REPOSITORY_ROOT, SITE_PORT, contentRoot, { indexFailures: FIRST_INDEX_FAILURES }),
    staticServer(INTERFACE_ROOT, INTERFACE_PORT),
]);
const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });

try {
    for (let cycle = 1; cycle <= CLEAN_CYCLES; cycle += 1) {
        // Loop: a fresh context detects leaked singleton, cache and tab state.
        const context = await browser.newContext();
        await context.addInitScript((configuration) => { window.BZNImageLibraryConfig = configuration; }, browserConfiguration());
        const page = await context.newPage();
        const errors = [];
        page.on('pageerror', (error) => errors.push(error.message));
        await page.goto(SITE_URL, { waitUntil: 'networkidle' });
        assert.equal(await page.locator('#openImageLibrary').isEnabled(), true, `cycle ${cycle}: missing index must not disable the shared UI`);
        await page.locator('#openImageLibrary:not([disabled])').click();
        const modal = page.locator('.bzn-resource-library-modal:not([hidden])');
        await modal.waitFor();
        assert.equal(await modal.locator('.bzn-resource-library-item').first().locator('img').getAttribute('alt'), `Browser ${FIXTURE_COUNT}.svg`, `cycle ${cycle}: newest API item must be first`);
        const previewBackground = await modal.locator('.bzn-resource-library-preview').first().evaluate((element) => getComputedStyle(element).backgroundImage);
        assert.match(previewBackground, /linear-gradient/, `cycle ${cycle}: image transparency checker`);
        const counts = [];
        for (let pageIndex = 0; pageIndex < EXPECTED_PAGE_COUNTS.length; pageIndex += 1) {
            // Loop: both pages keep one fixed window and expose the exact 30/4 split.
            const items = modal.locator('.bzn-resource-library-item');
            await items.first().waitFor();
            await page.waitForFunction(() => [...document.querySelectorAll('.bzn-resource-library-item img')].every((image) => image.complete && image.naturalWidth > 0));
            counts.push(await items.count());
            if (pageIndex < EXPECTED_PAGE_COUNTS.length - 1) await modal.locator('#bznResourceLibraryNext').click();
        }
        assert.deepEqual(counts, EXPECTED_PAGE_COUNTS);
        assert.match(await modal.locator('#bznResourceLibraryPage').textContent(), /2 \/ 2.*34/);
        await modal.locator('.bzn-resource-library-item').first().click();
        const lightbox = page.locator('.bzn-lightbox:not([hidden])');
        await lightbox.waitFor();
        assert.equal(await lightbox.getAttribute('data-lightbox-content-type'), 'Images');
        const lightboxBackground = await lightbox.locator('.bzn-lightbox-stage').evaluate((element) => getComputedStyle(element).backgroundImage);
        assert.match(lightboxBackground, /linear-gradient/, `cycle ${cycle}: Lightbox transparency checker`);
        assert.deepEqual(errors, []);
        await context.close();
        console.log(`Images browser cycle ${cycle}/${CLEAN_CYCLES} passed.`);
    }

    // Branch: a failed API retains the previously generated FTP index and usable shared gallery.
    const fallbackContext = await browser.newContext();
    const fallbackConfiguration = Object.freeze({
        ...browserConfiguration(),
        resourceEngine: Object.freeze({ ...browserConfiguration().resourceEngine, endpoint: STATIC_FALLBACK_ENDPOINT }),
    });
    await fallbackContext.addInitScript((configuration) => { window.BZNImageLibraryConfig = configuration; }, fallbackConfiguration);
    const fallbackPage = await fallbackContext.newPage();
    await fallbackPage.goto(SITE_URL, { waitUntil: 'networkidle' });
    await fallbackPage.locator('#openImageLibrary:not([disabled])').click();
    const fallbackModal = fallbackPage.locator('.bzn-resource-library-modal:not([hidden])');
    await fallbackModal.locator('.bzn-resource-library-item').first().waitFor();
    assert.equal(await fallbackModal.locator('.bzn-resource-library-item').count(), EXPECTED_PAGE_COUNTS[0]);
    await fallbackContext.close();
} finally {
    await browser.close();
    await Promise.all(servers.map((server) => new Promise((resolve) => server.close(resolve))));
}

console.log(`Images browser passed: ${FIXTURE_COUNT} items, pages ${EXPECTED_PAGE_COUNTS.join('/')}, Lightbox, ${CLEAN_CYCLES} clean cycles.`);
